/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NutCol: typeof import('@nutui/nutui-taro')['Col']
    NutDatePicker: typeof import('@nutui/nutui-taro')['DatePicker']
    NutEmpty: typeof import('@nutui/nutui-taro')['Empty']
    NutOverlay: typeof import('@nutui/nutui-taro')['Overlay']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutRow: typeof import('@nutui/nutui-taro')['Row']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
  }
}
